state:
  damage: '攻击'
  denfense: '防御'
  CritRate: '暴击几率'
  CritDouble: '暴击倍率'
  Critfense: '暴击抵抗'
  lifespawn: '回血'
  health: '血量'
  Speed: '移速'
  SuckhealthRate: '吸血几率'
  SuckhealthDouble: '吸血倍率'
  Damagerebound: '伤害反弹'
split: ":"